// EncryptionShlExt.idl : IDL source for EncryptionShlExt
//

// This file will be processed by the MIDL tool to
// produce the type library (EncryptionShlExt.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";

[
	object,
	uuid(c715a75a-0391-4b5c-83b1-6d713350b738),
	pointer_default(unique)
]
interface IShellExtension : IUnknown
{
};
[
	uuid(6d7ffa90-8339-45fa-8a0e-510b26868b29),
	version(1.0),
]
library EncryptionShlExtLib
{
	importlib("stdole2.tlb");
	[
		uuid(72c36a7a-ba29-42b2-bb49-bcc58bf4b945)
	]
	coclass ShellExtension
	{
		[default] interface IShellExtension;
	};
};

import "shobjidl.idl";
